version: "3"

services:
  db:
    image: postgres
    container_name: dbm
    hostname: dbmhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
